name: Tests & Build

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "created" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: ${{ github.ref_name }}
  ARTIFACT_NAME: artifact-${{ github.ref_name }}
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Test & Build
        run: ./gradlew build
        env:
          VERSION: ${{ env.VERSION }}

      - name: Store build artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Publish to Maven
        env:
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
